const quesitonList = [
  {
    //问题
    title:'您现在是否有发冷或发热',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'低热'},
      {value:'b',des:'高热(39以上)'},
      {value:'c',des:'时冷时热'},
      {value:'d',des:'发冷'},
      {value:'e',des:'正常'}
    ]
  },
  {
    //问题
    title:'您平时觉得身体怕冷还是怕热',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'怕冷'},
      {value:'b',des:'怕热'},
      {value:'c',des:'忽冷忽热'},
      {value:'d',des:'怕风'},
      {value:'e',des:'定时发热或定时热势加重'},
      {value:'f',des:'正常'}
    ]
  },
  {
    //问题
    title:'您平时是否容易出汗',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'易出汗'},
      {value:'b',des:'稍活动大汗淋漓'},
      {value:'c',des:'基本不出汗'},
      {value:'d',des:'手心易出汗'},
      {value:'e',des:'睡觉易出汗'},
      {value:'f',des:'半身出汗'},
      {value:'g',des:'仅头部出汗'},
      {value:'h',des:'正常'}
    ]
  },
  {
    //问题
    title:'您的头部，眼部是否有以下不适感',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'头晕'},
      {value:'b',des:'头痛'},
      {value:'c',des:'眼睛看东西模糊'},
      {value:'d',des:'眼睛干涩'},
      {value:'e',des:'眼睛肿胀'},
      {value:'f',des:'正常'}
    ]
  },
  {
    //问题
    title:'您的耳鼻喉是否有以下症状',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'耳鸣'},
      {value:'b',des:'耳聋'},
      {value:'c',des:'鼻塞'},
      {value:'d',des:'鼻流清涕'},
      {value:'e',des:'鼻流黄涕'},
      {value:'f',des:'鼻出血'},
      {value:'g',des:'咽喉干'},
      {value:'h',des:'咽喉痒'},
      {value:'i',des:'咽喉痛'},
      {value:'j',des:'正常'}
    ]
  },
  {
    //问题
    title:'您感觉口中有无异味',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'口淡'},
      {value:'b',des:'口苦'},
      {value:'c',des:'口甜'},
      {value:'d',des:'口酸'},
      {value:'e',des:'口咸'},
      {value:'f',des:'正常'},
    ]
  },
  {
    //问题
    title:'您感觉口中有无以下不适感',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'口舌粘腻'},
      {value:'b',des:'口臭'},
      {value:'c',des:'口腔溃疡'},
      {value:'d',des:'牙痛'},
      {value:'e',des:'牙龈出血'},
      {value:'f',des:'正常'},
    ]
  },
  {
    //问题
    title:'您的胃食道是否有以下症状',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'胃胀'},
      {value:'b',des:'胃痛'},
      {value:'c',des:'恶心'},
      {value:'d',des:'呕吐'},
      {value:'e',des:'反酸'},
      {value:'f',des:'打嗝'},
      {value:'g',des:'食道有烧灼感'},
      {value:'h',des:'正常'},
    ]
  },
  {
    //问题
    title:'您的胸部是否有不适感',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'胸痛'},
      {value:'b',des:'胸闷'},
      {value:'c',des:'心慌'},
      {value:'d',des:'气喘'},
      {value:'e',des:'气短'},
      {value:'f',des:'呼吸困难'},
      {value:'g',des:'正常'},
    ]
  },
  {
    //问题
    title:'您的腹部是否有不适感',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'腹痛'},
      {value:'b',des:'腹胀'},
      {value:'c',des:'有气从腹部上冲'},
      {value:'d',des:'咳嗽'},
      {value:'e',des:'咳痰'},
      {value:'f',des:'咳血'},
      {value:'g',des:'正常'},
    ]
  },
  {
    //问题
    title:'您的四肢是否有以下症状',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'四肢疼痛'},
      {value:'b',des:'四肢酸楚'},
      {value:'c',des:'四肢水肿'},
      {value:'d',des:'四肢麻木'},
      {value:'e',des:'四肢沉重'},
      {value:'f',des:'四肢无力'},
      {value:'g',des:'四肢抽筋'},
      {value:'h',des:'正常'},
    ]
  },
  {
    //问题
    title:'您的每天的大便次数',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'一天一次或隔天一次'},
      {value:'b',des:'一天几次'},
      {value:'c',des:'几天一次'},
      {value:'d',des:'长期便秘'},
    ]
  },
  {
    //问题
    title:'您的大便形状质地',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'大便偏干'},
      {value:'b',des:'大便偏稀'},
      {value:'c',des:'大便时干时稀'},
      {value:'d',des:'大便粘马桶'},
      {value:'e',des:'大便中有未消化食物'},
      {value:'f',des:'大便中有血'},
      {value:'g',des:'正常'},
    ]
  },
  {
    //问题
    title:'您的排便时是否有异常感',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'肛门有灼热感'},
      {value:'b',des:'腹痛有排便但排不尽'},
      {value:'c',des:'排便有不通畅'},
      {value:'d',des:'大便失禁'},
      {value:'e',des:'肛门沉重感或下坠感'},
      {value:'f',des:'正常'},
    ]
  },
  {
    //问题
    title:'您的小便如何',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'尿量增多'},
      {value:'b',des:'尿量减少'},
      {value:'c',des:'小便次数多'},
      {value:'d',des:'小便不畅'},
      {value:'e',des:'正常'},
    ]
  },
  {
    //问题
    title:'您的小便是什么颜色',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'小便色清'},
      {value:'b',des:'小便色黄'},
      {value:'c',des:'尿中带血'},
      {value:'d',des:'小便混浊'},
      {value:'e',des:'尿中有砂石'},
    ]
  },
  {
    //问题
    title:'您小便时是否有有异常感',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'尿道灼热'},
      {value:'b',des:'小便不畅'},
      {value:'c',des:'小便疼痛'},
      {value:'d',des:'排尿后小便点滴尿不尽'},
      {value:'e',des:'小便失禁'},
      {value:'f',des:'睡眠中不自主排尿'},
      {value:'g',des:'正常'},
    ]
  },
  {
    //问题
    title:'您的胃口食欲如何',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'食欲好'},
      {value:'b',des:'食欲不振'},
      {value:'c',des:'容易饿'},
      {value:'d',des:'饥饿但又不想进食'},
      {value:'e',des:'喜欢吃凉食'},
      {value:'f',des:'喜欢吃热食'},
      {value:'g',des:'正常'},
    ]
  },
  {
    //问题
    title:'您平时的饮水情况是怎么样的',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'口不渴'},
      {value:'b',des:'口渴多饮'},
      {value:'c',des:'口渴但不喜欢饮水'},
      {value:'d',des:'喜欢饮冷水'},
      {value:'e',des:'喜欢饮热水'},
      {value:'f',des:'正常'},
    ]
  },
  {
    //问题
    title:'您的睡眠质量如何',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'失眠'},
      {value:'b',des:'多梦'},
      {value:'c',des:'嗜睡'},
      {value:'d',des:'睡眠浅'},
      {value:'e',des:'睡眠磨牙'},
      {value:'f',des:'睡眠打呼'},
    ]
  },
  {
    //问题
    title:'您平时的精神情绪如何',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'疲倦'},
      {value:'b',des:'心烦'},
      {value:'c',des:'紧张'},
      {value:'d',des:'易受惊吓'},
      {value:'e',des:'焦虑'},
      {value:'f',des:'抑郁'},
      {value:'g',des:'易怒'},
      {value:'h',des:'正常'},
    ]
  },
  {
    //问题
    title:'您平时是否有以下不良生活习惯',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'喜欢吃辣'},
      {value:'b',des:'长期嗜酒'},
      {value:'c',des:'抽烟'},
      {value:'d',des:'三餐不规律'},
      {value:'e',des:'长期熬夜'},
      {value:'f',des:'长期高强度体力劳动'},
      {value:'g',des:'久坐'},
      {value:'h',des:'房事过度'},
      {value:'i',des:'均无'},
    ]
  },
  {
    //问题
    title:'您的经期情况是怎么样的（女）',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'闭经'},
      {value:'b',des:'月经提前'},
      {value:'c',des:'月经推迟'},
      {value:'d',des:'月经先后不定'},
      {value:'e',des:'正常'},
    ]
  },
  {
    //问题
    title:'您的经色经量是怎么样的（女）',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'经色鲜红'},
      {value:'b',des:'经色浅淡'},
      {value:'c',des:'经色紫暗'},
      {value:'d',des:'月经夹有血块'},
      {value:'e',des:'月经量少'},
      {value:'f',des:'月经量多'},
      {value:'g',des:'月经淋漓不尽'},
      {value:'h',des:'正常'},
    ]
  },
  {
    //问题
    title:'您的经期是否有伴随以下不适感(女)',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'痛经'},
      {value:'b',des:'经期发热'},
      {value:'c',des:'经期伴随腰部疼痛'},
      {value:'d',des:'经间期出血'},
      {value:'e',des:'经期头痛'},
      {value:'f',des:'经期头晕'},
      {value:'g',des:'经期乳房疼痛'},
      {value:'h',des:'均无'},
    ]
  },
  {
    //问题
    title:'您的白带是否有以下现象(女)',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'白带量多'},
      {value:'b',des:'白带量少'},
      {value:'c',des:'无白带'},
      {value:'d',des:'白带色黄'},
      {value:'e',des:'白带粘稠'},
      {value:'f',des:'白带腥臭'},
      {value:'g',des:'白带夹血'},
      {value:'h',des:'豆腐渣样白带'},
      {value:'i',des:'均无'},
    ]
  },
  
  
]
module.exports = quesitonList