const quesitonList = [
  {
    //问题
    title:'您现在是否有发冷或发热',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'低热'},
      {value:'b',des:'高热(39以上)'},
      {value:'c',des:'时冷时热'},
      {value:'d',des:'发冷'},
      {value:'e',des:'正常'}
    ]
  },
  {
    //问题
    title:'您平时觉得身体怕冷还是怕热',
    //选定的值
    value:[],
    //问题选项
    options:[
      {value:'a',des:'怕冷'},
      {value:'b',des:'怕热'},
      {value:'c',des:'忽冷忽热'},
      {value:'d',des:'怕风'},
      {value:'e',des:'定时发热或定时热势加重'},
      {value:'f',des:'正常'}
    ]
  }
]
module.exports = quesitonList